### ISSUE TITLE
BUG: Floats in strings are incorrectly rounded in formatted output

### ISSUE THREAD

**Issue by rafaelmagu** [dmlittle/scenery#28] opened 2019-04-18 03:41 UTC
It appears floats are being rounded incorrectly.

Original plan shows:

```
~ module.stack.module.eks-cluster.aws_eks_cluster.cluster
     version: "1.11" => "1.10"
```

Formatted output shows:

```
~ module.stack.module.eks-cluster.aws_eks_cluster.cluster
     version: "1.11" => "1.1"
```

As displayed on our Terraform pipeline:
![image](https://user-images.githubusercontent.com/197444/56335289-0a0a4000-61f0-11e9-8ca2-bd6fe19a93a4.png)

**Comment by dmlittle** [comment] 2019-04-18 05:58
@rafaelmagu thanks for reporting this issue!

It looks like this issue is being caused by the fact that the [`json.Unmarshal` function call](https://github.com/dmlittle/scenery/blob/be3f5758831413a15bafa8902ff161d25af96d52/pkg/printer/printer.go#L248) converts JSON numbers into floats and then loses its precision when printing it back again using [`json.MarshalIndent` to pretty print the output](https://github.com/dmlittle/scenery/blob/be3f5758831413a15bafa8902ff161d25af96d52/pkg/printer/printer.go#L253).

This looks like it can be fixed by using a JSON decoder and setting it to use a [json.Number](https://golang.org/pkg/encoding/json/#Number) so it print it's original value when it's marshaled again. 

I'll have a fix up soon!

**Closed** 2019-04-18 06:13 UTC
Labels: bug

**Comment by dmlittle** [comment] 2019-04-18 06:32
v0.1.5 has been released with these fixes.
